# Generated by Django 5.2.4 on 2026-08-05 14:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_car_carstatus_alter_car_carowner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['nameBrand'], 'verbose_name': 'Marca', 'verbose_name_plural': 'Marcas'},
        ),
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['modelCar'], 'verbose_name': 'Carro', 'verbose_name_plural': 'Carros'},
        ),
        migrations.AlterField(
            model_name='brand',
            name='nameBrand',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='factoryYear',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1975)]),
        ),
        migrations.AlterField(
            model_name='car',
            name='modelYear',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1975)]),
        ),
        migrations.AlterField(
            model_name='car',
            name='plateCar',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Placa inválida. Use o formato ABC1234 ou ABC1D23.', regex='^[A-Za-z]{3}-?\\d[A-Za-z0-9]\\d{2}$')]),
        ),
        migrations.AlterField(
            model_name='car',
            name='valueCar',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(20000)]),
        ),
    ]
