# Generated by Django 5.2.4 on 2026-08-05 15:10

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_alter_brand_options_alter_car_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='valueCar',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('20000'))]),
        ),
        migrations.AlterField(
            model_name='carinventory',
            name='carsValue',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
    ]
