# Generated by Django 5.2.4 on 2026-08-05 16:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0009_alter_car_valuecar_alter_carinventory_carsvalue'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cars/')),
                ('position', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Foto do carro',
                'verbose_name_plural': 'Fotos do carro',
                'ordering': ['position', 'id'],
            },
        ),
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['-createdAt', 'modelCar'], 'verbose_name': 'Carro', 'verbose_name_plural': 'Carros'},
        ),
        migrations.AddField(
            model_name='car',
            name='color',
            field=models.CharField(blank=True, max_length=30, verbose_name='Cor'),
        ),
        migrations.AddField(
            model_name='car',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='fuel',
            field=models.CharField(blank=True, choices=[('flex', 'Flex'), ('gasolina', 'Gasolina'), ('etanol', 'Etanol'), ('diesel', 'Diesel'), ('gnv', 'GNV'), ('eletrico', 'Elétrico'), ('hibrido', 'Híbrido')], max_length=10, verbose_name='Combustível'),
        ),
        migrations.AddField(
            model_name='car',
            name='mileage',
            field=models.PositiveIntegerField(blank=True, help_text='Em quilômetros rodados.', null=True, verbose_name='Quilometragem'),
        ),
        migrations.AddField(
            model_name='car',
            name='transmission',
            field=models.CharField(blank=True, choices=[('manual', 'Manual'), ('automatico', 'Automático'), ('automatizado', 'Automatizado'), ('cvt', 'CVT')], max_length=15, verbose_name='Câmbio'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['carStatus'], name='cars_car_carStat_325bea_idx'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['valueCar'], name='cars_car_valueCa_ad0e98_idx'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['factoryYear'], name='cars_car_factory_bbdb58_idx'),
        ),
        migrations.AddField(
            model_name='carphoto',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='cars.car'),
        ),
    ]
